apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-v2
  namespace: schema-demo
  labels:
    schema.version: v2
spec:
  broker: schema-broker
  filter:
    attributes:
      schemaversion: v2
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: consumer-v2
