apiVersion: v1
kind: Namespace
metadata:
  name: versioned-demo
  labels:
    app.kubernetes.io/part-of: versioned-demo
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
