apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: schema-demo
  labels:
    app.kubernetes.io/name: producer
    app.kubernetes.io/part-of: demo-schema-versioning
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: producer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: producer
    spec:
      containers:
        - name: producer
          image: dev.local/demo-producer:dev
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP
              value: redpanda.schema-demo.svc.cluster.local:9092
            - name: KAFKA_TOPIC
              value: events
            - name: ACTIVE_VERSIONS
              value: "v1,v2"
            - name: EMIT_INTERVAL_MS
              value: "1000"
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              memory: 256Mi
