apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: schema-broker
  namespace: schema-demo
  labels:
    tilt-bump: "1778773215"
  annotations:
    eventing.knative.dev/broker.class: Kafka
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: schema-demo
